server:
  port: 8092

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb+srv://bryanbenavente:PyZlRAr5ahRJZ80L@cluster0.2leex.mongodb.net/?retryWrites=true&w=majority
      database: coreografia
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    stream:
      kafka:
        streams:
          binder:
            functions:
              consumerProduct:
                applicationId: consumerProduct

      function:
        definition: consumerProduct;
      bindings:
        consumerProduct-in-0:
          destination: orders.buy
          consumer:
            maxAttempts: 1
