spring:
  data:
    mongodb:
      uri: <modificar>
      database: orquestacion
  application:
    name: product-service

server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
  instance:
    preferIpAddress: true
    hostName: 192.168.43.77
